# Generated by Django 5.0.7 on 2024-08-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(max_length=10, unique=True)),
                ('nome_curso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('meio_contato', models.CharField(choices=[('Email', 'Email'), ('Telefone', 'Telefone'), ('WhatsApp', 'WhatsApp'), ('Site', 'Site')], max_length=50)),
                ('como_soube', models.CharField(choices=[('Propaganda', 'Propaganda'), ('Indicação', 'Indicação'), ('Internet', 'Internet'), ('Outro', 'Outro')], max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('realizado_contato', models.BooleanField(default=False)),
                ('historico', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
            ],
        ),
    ]
