# Generated by Django 5.0.7 on 2024-08-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_interesse_realizado_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interesse',
            name='como_soube',
        ),
        migrations.RemoveField(
            model_name='interesse',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='interesse',
            name='data_registro',
        ),
        migrations.RemoveField(
            model_name='interesse',
            name='historico',
        ),
        migrations.RemoveField(
            model_name='interesse',
            name='meio_contato',
        ),
        migrations.RemoveField(
            model_name='interesse',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='interesse',
            name='realizado_contato',
        ),
        migrations.RemoveField(
            model_name='interesse',
            name='telefone',
        ),
        migrations.AddField(
            model_name='interesse',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9),
        ),
        migrations.AddField(
            model_name='interesse',
            name='cnpj',
            field=models.CharField(default='00.000.000/0000-00', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='interesse',
            name='data_envio',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='interesse',
            name='mensagem',
            field=models.TextField(default='Mensagem padrão'),
        ),
        migrations.AddField(
            model_name='interesse',
            name='nome_representante',
            field=models.CharField(default='Nome Padrão', max_length=100),
        ),
        migrations.AddField(
            model_name='interesse',
            name='pagina_site',
            field=models.URLField(default='http://www.site.com.br'),
        ),
        migrations.AddField(
            model_name='interesse',
            name='razao_social',
            field=models.CharField(default='Razão Social Padrão', max_length=100),
        ),
        migrations.AddField(
            model_name='interesse',
            name='telefone_comercial',
            field=models.CharField(default='(00) 0000-0000', max_length=20),
        ),
    ]
