# Generated by Django 5.0.7 on 2024-08-06 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_interesse_como_soube_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEdicaoInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizada_contato', models.CharField(max_length=100)),
                ('forma_contato', models.CharField(max_length=100)),
                ('numero_atendimento', models.UUIDField()),
                ('data_hora_registro', models.DateTimeField()),
                ('observacoes', models.TextField()),
                ('editado_em', models.DateTimeField(auto_now_add=True)),
                ('interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edicoes', to='core.interesse')),
            ],
        ),
    ]
