# Generated by Django 5.0.7 on 2024-08-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_interesse_cep_alter_interesse_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesse',
            name='pagina_site',
            field=models.CharField(blank=True, default='Origem', max_length=20),
        ),
    ]
