# Generated by Django 5.0.7 on 2024-08-10 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_interesse_pagina_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesse',
            name='data_hora_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
