# Generated by Django 5.0.7 on 2024-08-10 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_interesse_data_hora_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interesse',
            name='data_hora_criacao',
        ),
        migrations.AlterField(
            model_name='interesse',
            name='data_envio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
