# Generated by Django 5.0.7 on 2024-08-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_interesse_data_hora_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesse',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
