# Generated by Django 5.0.7 on 2024-08-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_interesse_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroedicaointeresse',
            name='usuario',
            field=models.CharField(default='usuario', max_length=150),
        ),
    ]
