# Generated by Django 5.0.7 on 2024-08-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_registroedicaointeresse_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroedicaointeresse',
            name='usuario',
            field=models.CharField(max_length=150),
        ),
    ]
