# Generated by Django 5.0.7 on 2024-08-14 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_interesse_pagina_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesse',
            name='data_envio',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
