# Generated by Django 5.0.7 on 2024-08-14 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_interesse_data_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesse',
            name='data_envio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
