# Generated by Django 5.0.7 on 2024-09-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_interesse_data_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroedicaointeresse',
            name='arquivo_evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/'),
        ),
    ]
