# Generated by Django 5.0.7 on 2024-11-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_registroedicaointeresse_arquivo_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesse',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interesse',
            name='motivo_inativacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
