# Generated by Django 5.0.7 on 2024-11-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_interesse_ativo_interesse_motivo_inativacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroedicaointeresse',
            name='motivo_inativacao',
            field=models.CharField(blank=True, choices=[('desistencia', 'Desistência'), ('matriculado', 'Já Matriculado'), ('concluiu', 'Já Fez o Curso'), ('nao_interesse', 'Não Tem Interesse'), ('outros', 'Outros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registroedicaointeresse',
            name='realizada_contato',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('inativo', 'Inativo')], default='nao', max_length=10),
        ),
    ]
