# Generated by Django 5.0.7 on 2024-11-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_registroedicaointeresse_motivo_inativacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroedicaointeresse',
            name='forma_contato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registroedicaointeresse',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroedicaointeresse',
            name='realizada_contato',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=10, null=True),
        ),
    ]
